version: '3'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secrect
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    volumes:
      - "pg-data:/var/lib/postgresql/data"
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  cardgame:
    container_name: 'cardgame'
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    ports:
      - '8000:8000'
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./projects/cardgame:/var/www
    command: "php artisan serve --host=0.0.0.0 --port=8000"
    # command: sh -c "tail -f /dev/null" // #TIP: use this to debug docker container without failing

volumes:
  pg-data:
    driver: local
  timescaledb-data:
    driver: local
  mongodb_data_container:
    driver: local
